 const ActionTypes = {
    USERNAME:'USERNAME',
    CURRENTUSER:'CURRENTUSER',
    ALLUSERS:'ALLUSERS',
    MESSAGES: 'MESSAGES',
    CHANGERECPUID: 'CHANGERECPUID',
    DATA:'DATA'
}

export default ActionTypes;
